<?php
/**
 * This file is part of the "Easy System" package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Damon Smith <damon.easy.system@gmail.com>
 */
?>

<span>

    <?php if (! empty($modules)): ?>

    <ul>

        <?php foreach($modules as $namespace => $version): ?>

        <li><pre><?= sprintf('%-26.26s %-8s', $namespace, $version) ?></pre></li>

        <?php endforeach ?>

    </ul>

    <?php endif ?>

    Modules: <?= count($modules) ?>

</span>
