<?php
/**
 * This file is part of the "Easy System" package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Damon Smith <damon.easy.system@gmail.com>
 */
?>

<span>

    <?php if (! empty($request_attributes)): ?>

    <ul>

        <?php foreach ($request_attributes as $name => $item): ?>

        <li><pre><?= $name . "\n" ?>(<?= $item ?>)</pre></li>

        <?php endforeach ?>

    </ul>

    <?php endif ?>

    Request attributes: <?= count($request_attributes) ?>

</span>
